// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Artifact is the predicate function for artifact builders.
type Artifact func(*sql.Selector)

// Identity is the predicate function for identity builders.
type Identity func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Version is the predicate function for version builders.
type Version func(*sql.Selector)
