// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Account defines model for Account.
type Account struct {
	AvatarUrl *string `json:"avatar_url,omitempty"`
	Email     string  `json:"email"`
	Id        string  `json:"id"`
	Name      *string `json:"name,omitempty"`
	Username  string  `json:"username"`
}

// Error defines model for Error.
type Error struct {
	Details *string `json:"details,omitempty"`
	Message string  `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Errors    []Error `json:"errors"`
	RequestID *string `json:"requestID,omitempty"`
}

// GoogleLoginRequest defines model for GoogleLoginRequest.
type GoogleLoginRequest struct {
	// IdToken A Google-issued OIDC ID token.
	IdToken string `json:"id_token"`
}

// Message defines model for Message.
type Message struct {
	Message string `json:"message"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	// RefreshToken A previously issued refresh token.
	RefreshToken string `json:"refresh_token"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	Subject      string `json:"subject"`
}

// UpdateAccountRequest defines model for UpdateAccountRequest.
type UpdateAccountRequest struct {
	Username string `json:"username"`
}

// Version defines model for Version.
type Version struct {
	CreatedAt time.Time `json:"created_at"`
	Sha256    string    `json:"sha256"`
	Version   int       `json:"version"`
}

// VersionList defines model for VersionList.
type VersionList struct {
	Versions []Version `json:"versions"`
}

// Name defines model for Name.
type Name = string

// Namespace defines model for Namespace.
type Namespace = string

// VersionParam defines model for VersionParam.
type VersionParam = int

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// PushVersionTextBody defines parameters for PushVersion.
type PushVersionTextBody = string

// UpdateAccountJSONRequestBody defines body for UpdateAccount for application/json ContentType.
type UpdateAccountJSONRequestBody = UpdateAccountRequest

// LoginWithGoogleJSONRequestBody defines body for LoginWithGoogle for application/json ContentType.
type LoginWithGoogleJSONRequestBody = GoogleLoginRequest

// RefreshTokensJSONRequestBody defines body for RefreshTokens for application/json ContentType.
type RefreshTokensJSONRequestBody = RefreshRequest

// PushVersionTextRequestBody defines body for PushVersion for text/plain ContentType.
type PushVersionTextRequestBody = PushVersionTextBody

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// Health Liveness check
	//
	// Corresponds with GET /health (the `Health` operationId).
	Health(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteAccount Delete the authenticated account
	//
	// Removes the account and cascades to its identities and artifacts.
	//
	// Corresponds with DELETE /v1/account (the `DeleteAccount` operationId).
	DeleteAccount(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAccount Get the authenticated account
	//
	// Corresponds with GET /v1/account (the `GetAccount` operationId).
	GetAccount(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateAccountWithBody Update the authenticated account's username
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PATCH /v1/account (the `UpdateAccount` operationId).
	UpdateAccountWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateAccount Update the authenticated account's username
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with PATCH /v1/account (the `UpdateAccount` operationId).
	UpdateAccount(ctx context.Context, body UpdateAccountJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// LoginWithGoogleWithBody Exchange a Google ID token for the registry's own token pair
	//
	// The client obtains a Google ID token via its own browser/PKCE (CLI) or Google Identity Services (web) flow and posts it here. The server verifies it, create-or-links the account, and returns our access/refresh tokens. Every other endpoint authenticates with our access token.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/tokens/google (the `LoginWithGoogle` operationId).
	LoginWithGoogleWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// LoginWithGoogle Exchange a Google ID token for the registry's own token pair
	//
	// The client obtains a Google ID token via its own browser/PKCE (CLI) or Google Identity Services (web) flow and posts it here. The server verifies it, create-or-links the account, and returns our access/refresh tokens. Every other endpoint authenticates with our access token.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v1/tokens/google (the `LoginWithGoogle` operationId).
	LoginWithGoogle(ctx context.Context, body LoginWithGoogleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RefreshTokensWithBody Exchange a refresh token for a new access/refresh token pair
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/tokens/refresh (the `RefreshTokens` operationId).
	RefreshTokensWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RefreshTokens Exchange a refresh token for a new access/refresh token pair
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v1/tokens/refresh (the `RefreshTokens` operationId).
	RefreshTokens(ctx context.Context, body RefreshTokensJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListVersions List the versions of an artifact
	//
	// Corresponds with GET /v1/{namespace}/{name} (the `ListVersions` operationId).
	ListVersions(ctx context.Context, namespace Namespace, name Name, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PushVersionWithBody Push a new immutable version
	//
	// Uploads the raw `.evoke` document as a new immutable version of {namespace}/{name}, creating the artifact (owned by the caller) on first push and assigning the next version number.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PUT /v1/{namespace}/{name} (the `PushVersion` operationId).
	PushVersionWithBody(ctx context.Context, namespace Namespace, name Name, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PushVersionWithTextBody Push a new immutable version
	//
	// Uploads the raw `.evoke` document as a new immutable version of {namespace}/{name}, creating the artifact (owned by the caller) on first push and assigning the next version number.
	//
	// Takes a body of the `text/plain` content type.
	//
	// Corresponds with PUT /v1/{namespace}/{name} (the `PushVersion` operationId).
	PushVersionWithTextBody(ctx context.Context, namespace Namespace, name Name, body PushVersionTextRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetVersion Pull the raw bytes of a specific version
	//
	// Corresponds with GET /v1/{namespace}/{name}/{version} (the `GetVersion` operationId).
	GetVersion(ctx context.Context, namespace Namespace, name Name, version VersionParam, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// Health Liveness check
//
// Corresponds with GET /health (the `Health` operationId).
func (c *Client) Health(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeleteAccount Delete the authenticated account
//
// Removes the account and cascades to its identities and artifacts.
//
// Corresponds with DELETE /v1/account (the `DeleteAccount` operationId).
func (c *Client) DeleteAccount(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteAccountRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetAccount Get the authenticated account
//
// Corresponds with GET /v1/account (the `GetAccount` operationId).
func (c *Client) GetAccount(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAccountRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpdateAccountWithBody Update the authenticated account's username
//
// Takes any type of body and a specified content type.
//
// Corresponds with PATCH /v1/account (the `UpdateAccount` operationId).
func (c *Client) UpdateAccountWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateAccountRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpdateAccount Update the authenticated account's username
//
// Takes a body of the `application/json` content type.
//
// Corresponds with PATCH /v1/account (the `UpdateAccount` operationId).
func (c *Client) UpdateAccount(ctx context.Context, body UpdateAccountJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateAccountRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// LoginWithGoogleWithBody Exchange a Google ID token for the registry's own token pair
//
// The client obtains a Google ID token via its own browser/PKCE (CLI) or Google Identity Services (web) flow and posts it here. The server verifies it, create-or-links the account, and returns our access/refresh tokens. Every other endpoint authenticates with our access token.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/tokens/google (the `LoginWithGoogle` operationId).
func (c *Client) LoginWithGoogleWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLoginWithGoogleRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// LoginWithGoogle Exchange a Google ID token for the registry's own token pair
//
// The client obtains a Google ID token via its own browser/PKCE (CLI) or Google Identity Services (web) flow and posts it here. The server verifies it, create-or-links the account, and returns our access/refresh tokens. Every other endpoint authenticates with our access token.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /v1/tokens/google (the `LoginWithGoogle` operationId).
func (c *Client) LoginWithGoogle(ctx context.Context, body LoginWithGoogleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLoginWithGoogleRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// RefreshTokensWithBody Exchange a refresh token for a new access/refresh token pair
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/tokens/refresh (the `RefreshTokens` operationId).
func (c *Client) RefreshTokensWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRefreshTokensRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// RefreshTokens Exchange a refresh token for a new access/refresh token pair
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /v1/tokens/refresh (the `RefreshTokens` operationId).
func (c *Client) RefreshTokens(ctx context.Context, body RefreshTokensJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRefreshTokensRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListVersions List the versions of an artifact
//
// Corresponds with GET /v1/{namespace}/{name} (the `ListVersions` operationId).
func (c *Client) ListVersions(ctx context.Context, namespace Namespace, name Name, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListVersionsRequest(c.Server, namespace, name)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PushVersionWithBody Push a new immutable version
//
// Uploads the raw `.evoke` document as a new immutable version of {namespace}/{name}, creating the artifact (owned by the caller) on first push and assigning the next version number.
//
// Takes any type of body and a specified content type.
//
// Corresponds with PUT /v1/{namespace}/{name} (the `PushVersion` operationId).
func (c *Client) PushVersionWithBody(ctx context.Context, namespace Namespace, name Name, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPushVersionRequestWithBody(c.Server, namespace, name, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PushVersionWithTextBody Push a new immutable version
//
// Uploads the raw `.evoke` document as a new immutable version of {namespace}/{name}, creating the artifact (owned by the caller) on first push and assigning the next version number.
//
// Takes a body of the `text/plain` content type.
//
// Corresponds with PUT /v1/{namespace}/{name} (the `PushVersion` operationId).
func (c *Client) PushVersionWithTextBody(ctx context.Context, namespace Namespace, name Name, body PushVersionTextRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPushVersionRequestWithTextBody(c.Server, namespace, name, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetVersion Pull the raw bytes of a specific version
//
// Corresponds with GET /v1/{namespace}/{name}/{version} (the `GetVersion` operationId).
func (c *Client) GetVersion(ctx context.Context, namespace Namespace, name Name, version VersionParam, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetVersionRequest(c.Server, namespace, name, version)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewHealthRequest constructs an http.Request for the Health method
func NewHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeleteAccountRequest constructs an http.Request for the DeleteAccount method
func NewDeleteAccountRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/account")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetAccountRequest constructs an http.Request for the GetAccount method
func NewGetAccountRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/account")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateAccountRequest calls the generic UpdateAccount builder with application/json body
func NewUpdateAccountRequest(server string, body UpdateAccountJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateAccountRequestWithBody(server, "application/json", bodyReader)
}

// NewUpdateAccountRequestWithBody constructs an http.Request for the UpdateAccount method, with any body, and a specified content type
func NewUpdateAccountRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/account")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPatch, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewLoginWithGoogleRequest calls the generic LoginWithGoogle builder with application/json body
func NewLoginWithGoogleRequest(server string, body LoginWithGoogleJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewLoginWithGoogleRequestWithBody(server, "application/json", bodyReader)
}

// NewLoginWithGoogleRequestWithBody constructs an http.Request for the LoginWithGoogle method, with any body, and a specified content type
func NewLoginWithGoogleRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/tokens/google")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewRefreshTokensRequest calls the generic RefreshTokens builder with application/json body
func NewRefreshTokensRequest(server string, body RefreshTokensJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRefreshTokensRequestWithBody(server, "application/json", bodyReader)
}

// NewRefreshTokensRequestWithBody constructs an http.Request for the RefreshTokens method, with any body, and a specified content type
func NewRefreshTokensRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/tokens/refresh")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListVersionsRequest constructs an http.Request for the ListVersions method
func NewListVersionsRequest(server string, namespace Namespace, name Name) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "namespace", namespace, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "name", name, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/%s/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPushVersionRequestWithTextBody calls the generic PushVersion builder with text/plain body
func NewPushVersionRequestWithTextBody(server string, namespace Namespace, name Name, body PushVersionTextRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	if stringer, ok := interface{}(body).(fmt.Stringer); ok {
		bodyReader = strings.NewReader(stringer.String())
	} else {
		bodyReader = strings.NewReader(fmt.Sprint(body))
	}
	return NewPushVersionRequestWithBody(server, namespace, name, "text/plain", bodyReader)
}

// NewPushVersionRequestWithBody constructs an http.Request for the PushVersion method, with any body, and a specified content type
func NewPushVersionRequestWithBody(server string, namespace Namespace, name Name, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "namespace", namespace, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "name", name, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/%s/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetVersionRequest constructs an http.Request for the GetVersion method
func NewGetVersionRequest(server string, namespace Namespace, name Name, version VersionParam) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "namespace", namespace, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "name", name, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithOptions("simple", false, "version", version, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/%s/%s/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// HealthWithResponse Liveness check
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /health (the `Health` operationId).
	HealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthResponse, error)

	// DeleteAccountWithResponse Delete the authenticated account
	//
	// Removes the account and cascades to its identities and artifacts.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /v1/account (the `DeleteAccount` operationId).
	DeleteAccountWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*DeleteAccountResponse, error)

	// GetAccountWithResponse Get the authenticated account
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /v1/account (the `GetAccount` operationId).
	GetAccountWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAccountResponse, error)

	// UpdateAccountWithBodyWithResponse Update the authenticated account's username
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PATCH /v1/account (the `UpdateAccount` operationId).
	UpdateAccountWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateAccountResponse, error)

	// UpdateAccountWithResponse Update the authenticated account's username
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PATCH /v1/account (the `UpdateAccount` operationId).
	UpdateAccountWithResponse(ctx context.Context, body UpdateAccountJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateAccountResponse, error)

	// LoginWithGoogleWithBodyWithResponse Exchange a Google ID token for the registry's own token pair
	//
	// The client obtains a Google ID token via its own browser/PKCE (CLI) or Google Identity Services (web) flow and posts it here. The server verifies it, create-or-links the account, and returns our access/refresh tokens. Every other endpoint authenticates with our access token.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/tokens/google (the `LoginWithGoogle` operationId).
	LoginWithGoogleWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*LoginWithGoogleResponse, error)

	// LoginWithGoogleWithResponse Exchange a Google ID token for the registry's own token pair
	//
	// The client obtains a Google ID token via its own browser/PKCE (CLI) or Google Identity Services (web) flow and posts it here. The server verifies it, create-or-links the account, and returns our access/refresh tokens. Every other endpoint authenticates with our access token.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/tokens/google (the `LoginWithGoogle` operationId).
	LoginWithGoogleWithResponse(ctx context.Context, body LoginWithGoogleJSONRequestBody, reqEditors ...RequestEditorFn) (*LoginWithGoogleResponse, error)

	// RefreshTokensWithBodyWithResponse Exchange a refresh token for a new access/refresh token pair
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/tokens/refresh (the `RefreshTokens` operationId).
	RefreshTokensWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RefreshTokensResponse, error)

	// RefreshTokensWithResponse Exchange a refresh token for a new access/refresh token pair
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/tokens/refresh (the `RefreshTokens` operationId).
	RefreshTokensWithResponse(ctx context.Context, body RefreshTokensJSONRequestBody, reqEditors ...RequestEditorFn) (*RefreshTokensResponse, error)

	// ListVersionsWithResponse List the versions of an artifact
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /v1/{namespace}/{name} (the `ListVersions` operationId).
	ListVersionsWithResponse(ctx context.Context, namespace Namespace, name Name, reqEditors ...RequestEditorFn) (*ListVersionsResponse, error)

	// PushVersionWithBodyWithResponse Push a new immutable version
	//
	// Uploads the raw `.evoke` document as a new immutable version of {namespace}/{name}, creating the artifact (owned by the caller) on first push and assigning the next version number.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /v1/{namespace}/{name} (the `PushVersion` operationId).
	PushVersionWithBodyWithResponse(ctx context.Context, namespace Namespace, name Name, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PushVersionResponse, error)

	// PushVersionWithTextBodyWithResponse Push a new immutable version
	//
	// Uploads the raw `.evoke` document as a new immutable version of {namespace}/{name}, creating the artifact (owned by the caller) on first push and assigning the next version number.
	//
	// Takes a body of the `text/plain` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /v1/{namespace}/{name} (the `PushVersion` operationId).
	PushVersionWithTextBodyWithResponse(ctx context.Context, namespace Namespace, name Name, body PushVersionTextRequestBody, reqEditors ...RequestEditorFn) (*PushVersionResponse, error)

	// GetVersionWithResponse Pull the raw bytes of a specific version
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /v1/{namespace}/{name}/{version} (the `GetVersion` operationId).
	GetVersionWithResponse(ctx context.Context, namespace Namespace, name Name, version VersionParam, reqEditors ...RequestEditorFn) (*GetVersionResponse, error)
}

type HealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Message
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r HealthResponse) GetJSON200() *Message {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r HealthResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r HealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r HealthResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteAccountResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFound
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r DeleteAccountResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r DeleteAccountResponse) GetJSON404() *NotFound {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r DeleteAccountResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DeleteAccountResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteAccountResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteAccountResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetAccountResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Account
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFound
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetAccountResponse) GetJSON200() *Account {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r GetAccountResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetAccountResponse) GetJSON404() *NotFound {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r GetAccountResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetAccountResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAccountResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetAccountResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type UpdateAccountResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Account
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *BadRequest
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFound
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Conflict
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r UpdateAccountResponse) GetJSON200() *Account {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r UpdateAccountResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r UpdateAccountResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r UpdateAccountResponse) GetJSON404() *NotFound {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r UpdateAccountResponse) GetJSON409() *Conflict {
	return r.JSON409
}

// GetBody returns the raw response body bytes
func (r UpdateAccountResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r UpdateAccountResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateAccountResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UpdateAccountResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type LoginWithGoogleResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *TokenResponse
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *BadRequest
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r LoginWithGoogleResponse) GetJSON200() *TokenResponse {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r LoginWithGoogleResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r LoginWithGoogleResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetBody returns the raw response body bytes
func (r LoginWithGoogleResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r LoginWithGoogleResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r LoginWithGoogleResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r LoginWithGoogleResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type RefreshTokensResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *TokenResponse
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *BadRequest
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r RefreshTokensResponse) GetJSON200() *TokenResponse {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r RefreshTokensResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r RefreshTokensResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetBody returns the raw response body bytes
func (r RefreshTokensResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r RefreshTokensResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RefreshTokensResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RefreshTokensResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListVersionsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *VersionList
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFound
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListVersionsResponse) GetJSON200() *VersionList {
	return r.JSON200
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r ListVersionsResponse) GetJSON404() *NotFound {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r ListVersionsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListVersionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListVersionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListVersionsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PushVersionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *Version
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *BadRequest
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r PushVersionResponse) GetJSON201() *Version {
	return r.JSON201
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r PushVersionResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r PushVersionResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetBody returns the raw response body bytes
func (r PushVersionResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PushVersionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PushVersionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PushVersionResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetVersionResponse200Headers the declared response headers of an HTTP 200 response for GetVersion
type GetVersionResponse200Headers struct {
	XEvokeSHA256 *string
}

type GetVersionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *BadRequest
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFound
	// Headers200 the parsed response headers for an HTTP 200 response
	Headers200 *GetVersionResponse200Headers
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r GetVersionResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetVersionResponse) GetJSON404() *NotFound {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r GetVersionResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetVersionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetVersionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetVersionResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// HealthWithResponse Liveness check
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /health (the `Health` operationId).
func (c *ClientWithResponses) HealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthResponse, error) {
	rsp, err := c.Health(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHealthResponse(rsp)
}

// DeleteAccountWithResponse Delete the authenticated account
//
// Removes the account and cascades to its identities and artifacts.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /v1/account (the `DeleteAccount` operationId).
func (c *ClientWithResponses) DeleteAccountWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*DeleteAccountResponse, error) {
	rsp, err := c.DeleteAccount(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteAccountResponse(rsp)
}

// GetAccountWithResponse Get the authenticated account
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /v1/account (the `GetAccount` operationId).
func (c *ClientWithResponses) GetAccountWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAccountResponse, error) {
	rsp, err := c.GetAccount(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAccountResponse(rsp)
}

// UpdateAccountWithBodyWithResponse Update the authenticated account's username
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PATCH /v1/account (the `UpdateAccount` operationId).
func (c *ClientWithResponses) UpdateAccountWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateAccountResponse, error) {
	rsp, err := c.UpdateAccountWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateAccountResponse(rsp)
}

// UpdateAccountWithResponse Update the authenticated account's username
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PATCH /v1/account (the `UpdateAccount` operationId).
func (c *ClientWithResponses) UpdateAccountWithResponse(ctx context.Context, body UpdateAccountJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateAccountResponse, error) {
	rsp, err := c.UpdateAccount(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateAccountResponse(rsp)
}

// LoginWithGoogleWithBodyWithResponse Exchange a Google ID token for the registry's own token pair
//
// The client obtains a Google ID token via its own browser/PKCE (CLI) or Google Identity Services (web) flow and posts it here. The server verifies it, create-or-links the account, and returns our access/refresh tokens. Every other endpoint authenticates with our access token.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/tokens/google (the `LoginWithGoogle` operationId).
func (c *ClientWithResponses) LoginWithGoogleWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*LoginWithGoogleResponse, error) {
	rsp, err := c.LoginWithGoogleWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLoginWithGoogleResponse(rsp)
}

// LoginWithGoogleWithResponse Exchange a Google ID token for the registry's own token pair
//
// The client obtains a Google ID token via its own browser/PKCE (CLI) or Google Identity Services (web) flow and posts it here. The server verifies it, create-or-links the account, and returns our access/refresh tokens. Every other endpoint authenticates with our access token.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/tokens/google (the `LoginWithGoogle` operationId).
func (c *ClientWithResponses) LoginWithGoogleWithResponse(ctx context.Context, body LoginWithGoogleJSONRequestBody, reqEditors ...RequestEditorFn) (*LoginWithGoogleResponse, error) {
	rsp, err := c.LoginWithGoogle(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLoginWithGoogleResponse(rsp)
}

// RefreshTokensWithBodyWithResponse Exchange a refresh token for a new access/refresh token pair
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/tokens/refresh (the `RefreshTokens` operationId).
func (c *ClientWithResponses) RefreshTokensWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RefreshTokensResponse, error) {
	rsp, err := c.RefreshTokensWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRefreshTokensResponse(rsp)
}

// RefreshTokensWithResponse Exchange a refresh token for a new access/refresh token pair
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/tokens/refresh (the `RefreshTokens` operationId).
func (c *ClientWithResponses) RefreshTokensWithResponse(ctx context.Context, body RefreshTokensJSONRequestBody, reqEditors ...RequestEditorFn) (*RefreshTokensResponse, error) {
	rsp, err := c.RefreshTokens(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRefreshTokensResponse(rsp)
}

// ListVersionsWithResponse List the versions of an artifact
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /v1/{namespace}/{name} (the `ListVersions` operationId).
func (c *ClientWithResponses) ListVersionsWithResponse(ctx context.Context, namespace Namespace, name Name, reqEditors ...RequestEditorFn) (*ListVersionsResponse, error) {
	rsp, err := c.ListVersions(ctx, namespace, name, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListVersionsResponse(rsp)
}

// PushVersionWithBodyWithResponse Push a new immutable version
//
// Uploads the raw `.evoke` document as a new immutable version of {namespace}/{name}, creating the artifact (owned by the caller) on first push and assigning the next version number.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /v1/{namespace}/{name} (the `PushVersion` operationId).
func (c *ClientWithResponses) PushVersionWithBodyWithResponse(ctx context.Context, namespace Namespace, name Name, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PushVersionResponse, error) {
	rsp, err := c.PushVersionWithBody(ctx, namespace, name, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePushVersionResponse(rsp)
}

// PushVersionWithTextBodyWithResponse Push a new immutable version
//
// Uploads the raw `.evoke` document as a new immutable version of {namespace}/{name}, creating the artifact (owned by the caller) on first push and assigning the next version number.
//
// Takes a body of the `text/plain` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /v1/{namespace}/{name} (the `PushVersion` operationId).
func (c *ClientWithResponses) PushVersionWithTextBodyWithResponse(ctx context.Context, namespace Namespace, name Name, body PushVersionTextRequestBody, reqEditors ...RequestEditorFn) (*PushVersionResponse, error) {
	rsp, err := c.PushVersionWithTextBody(ctx, namespace, name, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePushVersionResponse(rsp)
}

// GetVersionWithResponse Pull the raw bytes of a specific version
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /v1/{namespace}/{name}/{version} (the `GetVersion` operationId).
func (c *ClientWithResponses) GetVersionWithResponse(ctx context.Context, namespace Namespace, name Name, version VersionParam, reqEditors ...RequestEditorFn) (*GetVersionResponse, error) {
	rsp, err := c.GetVersion(ctx, namespace, name, version, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetVersionResponse(rsp)
}

// ParseHealthResponse parses an HTTP response from a HealthWithResponse call
func ParseHealthResponse(rsp *http.Response) (*HealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Message
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseDeleteAccountResponse parses an HTTP response from a DeleteAccountWithResponse call
func ParseDeleteAccountResponse(rsp *http.Response) (*DeleteAccountResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteAccountResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetAccountResponse parses an HTTP response from a GetAccountWithResponse call
func ParseGetAccountResponse(rsp *http.Response) (*GetAccountResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAccountResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Account
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseUpdateAccountResponse parses an HTTP response from a UpdateAccountWithResponse call
func ParseUpdateAccountResponse(rsp *http.Response) (*UpdateAccountResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateAccountResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Account
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParseLoginWithGoogleResponse parses an HTTP response from a LoginWithGoogleWithResponse call
func ParseLoginWithGoogleResponse(rsp *http.Response) (*LoginWithGoogleResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &LoginWithGoogleResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TokenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseRefreshTokensResponse parses an HTTP response from a RefreshTokensWithResponse call
func ParseRefreshTokensResponse(rsp *http.Response) (*RefreshTokensResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RefreshTokensResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TokenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseListVersionsResponse parses an HTTP response from a ListVersionsWithResponse call
func ParseListVersionsResponse(rsp *http.Response) (*ListVersionsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListVersionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest VersionList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParsePushVersionResponse parses an HTTP response from a PushVersionWithResponse call
func ParsePushVersionResponse(rsp *http.Response) (*PushVersionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PushVersionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Version
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseGetVersionResponse parses an HTTP response from a GetVersionWithResponse call
func ParseGetVersionResponse(rsp *http.Response) (*GetVersionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetVersionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	switch {
	case rsp.StatusCode == 200:
		var headers GetVersionResponse200Headers
		if values := rsp.Header.Values("X-Evoke-SHA256"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "X-Evoke-SHA256", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.XEvokeSHA256 = &value
		}
		response.Headers200 = &headers
	}

	return response, nil
}
